
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ci]

jobs:
  build:
    strategy:
      matrix:
        runtime:
          - win-x64
          - linux-x64-openssl3
          - linux-x64-openssl1
          - linux-arm
        include:
          - runtime: win-x64
            name: win-x64
            os: windows-latest
          - runtime: linux-x64-openssl3
            name: linux-x64
            os: ubuntu-22.04
          - runtime: linux-x64-openssl1
            name: linux-x64
            os: ubuntu-20.04
          - runtime: linux-arm
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›ï¸ Checkout 
        uses: actions/checkout@master
        with:
          persist-credentials: false
          
      - name: Check OpenSSL version
        if: startsWith(matrix.runtime, 'linux-x64')
        run: echo "OPENSSL_VERSION=$(openssl version | grep -oP '\d+\.\d+\.\d+[a-z]*' | head -n 1)" >> $GITHUB_OUTPUT
        id: check_openssl

      - name: ğŸ—ï¸ Build x64
        if: startsWith(matrix.runtime, 'linux-x64') || startsWith(matrix.runtime, 'win-x64')
        run: cargo build
      
      - name: ğŸ“± Build for arm
        if: startsWith(matrix.runtime, 'linux-arm')
        uses: pguyot/arm-runner-action@v2
        with:
          image: ./target/debug/yaytapi
          image_additional_mb: 500
          bind_mount_repository: true
          commands: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            cargo build

      - name: ğŸšš Move all output files into the same dir
        run: |
          mkdir dist/
          cp target/debug/yaytapi* dist/
          cp -r static/ dist/

      - name: ğŸ“¦ Publish artifact
        if: startsWith(matrix.runtime, 'win-x64')
        uses: actions/upload-artifact@v3
        with:
          name: yaytapi-${{ matrix.runtime }}
          path: dist/

      - name: ğŸ“¦ Publish artifact
        if: startsWith(matrix.runtime, 'linux-x64')
        uses: actions/upload-artifact@v3
        with:
          name: yaytapi-${{ matrix.name }}-openssl${{ steps.check_openssl.outputs.OPENSSL_VERSION }}
          path: dist/
          
      - name: ğŸ“¦ Publish artifact
        if: startsWith(matrix.runtime, 'linux-arm')
        uses: actions/upload-artifact@v3
        with:
          name: yaytapi-${{ matrix.name }}
          path: dist/
