
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ci]

jobs:
  build:
    strategy:
      matrix:
        runtime:
          - win-x64
          - linux-x64-openssl3
          - linux-x64-openssl1
          - linux-arm
        include:
          - runtime: win-x64
            name: win-x64
            os: windows-latest
          - runtime: linux-x64-openssl3
            name: linux-x64
            os: ubuntu-22.04
          - runtime: linux-x64-openssl1
            name: linux-x64
            os: ubuntu-20.04
          - runtime: linux-arm
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›ï¸ Checkout 
        uses: actions/checkout@master
        with:
          persist-credentials: false
          
      - name: Check OpenSSL version
        if: startsWith(matrix.runtime, 'linux-x64')
        run: echo "OPENSSL_VERSION=$(openssl version | grep -oP '\d+\.\d+\.\d+[a-z]*' | head -n 1)" >> $GITHUB_OUTPUT
        id: check_openssl

      - name: ğŸ—ï¸ Build x64
        if: startsWith(matrix.runtime, 'linux-x64') || startsWith(matrix.runtime, 'win-x64')
        run: cargo build
      
      - name: â¬‡ Clone `yayti` 4 arm
        if: startsWith(matrix.runtime, 'linux-arm')
        run: |
          git clone https://github.com/MarmadileManteater/yayti.git
          cd yayti
          git fetch --all
          git pull --all
          grep -E 'branch = "' ./Cargo.toml
          VERSION=$(grep -Eo 'branch = "([0-9.]*)"' ./Cargo.toml | sed 's/[^0-9.]//g')
          echo $VERSION
          git checkout $VERSION
          cd ../
          sed -i 's@git = "https://github.com/MarmadileManteater/yayti@path = "yayti@' ./Cargo.toml
          sed -i 's@branch = "$VERSION", version = "$VERSION",@@' ./Cargo.toml
          cat Cargo.toml
      
      - name: ğŸ“± Build for arm
        if: startsWith(matrix.runtime, 'linux-arm')
        uses: pguyot/arm-runner-action@v2
        with:
          image: ./target/debug/yaytapi
          image_additional_mb: 2048
          bind_mount_repository: true
          shell: /bin/bash
          commands: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source "$HOME/.cargo/env" 
            cargo build

      - name: ğŸšš Move all output files into the same dir
        run: |
          mkdir dist/
          cp target/debug/yaytapi* dist/
          cp -r static/ dist/

      - name: ğŸ“¦ Publish artifact
        if: startsWith(matrix.runtime, 'win-x64')
        uses: actions/upload-artifact@v3
        with:
          name: yaytapi-${{ matrix.runtime }}
          path: dist/

      - name: ğŸ“¦ Publish artifact
        if: startsWith(matrix.runtime, 'linux-x64')
        uses: actions/upload-artifact@v3
        with:
          name: yaytapi-${{ matrix.name }}-openssl${{ steps.check_openssl.outputs.OPENSSL_VERSION }}
          path: dist/
          
      - name: ğŸ“¦ Publish artifact
        if: startsWith(matrix.runtime, 'linux-arm')
        uses: actions/upload-artifact@v3
        with:
          name: yaytapi-${{ matrix.name }}
          path: dist/
